### ISSUE TITLE
I am getting error when run gulp 

### ISSUE THREAD

**Issue by athimannil** [ericlbarnes/gulp-bower-bootstrap-fontawesome#4]
Here is error message getting in terminal when run `gulp`. 

![gulp](https://cloud.githubusercontent.com/assets/4364227/10456989/2ce3e90a-71d5-11e5-92c0-6fbb590966f4.png)

**Comment by ericlbarnes** [comment]
My guess is in `gulpfile.js` on line 26 and 27 the path has changed: 
https://github.com/ericbarnes/gulp-bower-bootstrap-fontawesome/blob/master/gulpfile.js#L27

When this was originally written the path to bootstrap was: 

```
./bower_components/bootstrap-sass-official/assets/stylesheets
```

You may want to double check that is still the same.

**Comment by athimannil** [comment]
@ericbarnes I think the issue is `gulp-ruby-sass` version. The gulp plugin gulp-ruby-sass doesn't work "gulp-ruby-sass": "^2.0.4" for the compiler at the same time it does work with its own old version "gulp-ruby-sass": "^0.7.1"

<img width="924" alt="gulp" src="https://cloud.githubusercontent.com/assets/4364227/10464215/b3e4d166-71f9-11e5-9f13-5626149a7619.png">

**Comment by ericlbarnes** [comment]
So this might be related to #2 

I know when I first wrote this tutorial it worked fine, the gulp-ruby-sass had a new version which broke it. But I assumed it would be fixed by now.

**Comment by athimannil** [comment]
@ericbarnes by the way I forget to say thanks for your tutorial. As a beginner in gulp your tutorials helped me a lot.

**Comment by athimannil** [comment]
@ericbarnes do you think the git works with https://github.com/dlmanning/gulp-sass ?

**Comment by ericlbarnes** [comment]
Yes it should. 

I think you can also change the gulpfile and remove the `loadPath` since it doesn't support that. Then in your `style.scss`: 

```
@import "bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap";
```

**Comment by athimannil** [comment]
you( @ericbarnes ) mean go 

```
@import "variables";
@import "../bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
$fa-font-path: "../bower_components/font-awesome/fonts";
@import "../bower_components/font-awesome/scss/font-awesome";
@import "general.scss";
```

like this in `styles.scss` ?
